version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/frontend"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"   
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      rust-dependencies:
        patterns:
          - "*"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/frontend"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-dependencies:
        patterns:
          - "*"
