name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  frontend:
    name: Frontend Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm run lint
    
  typescript:
    name: Typescript Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npx tsc --noEmit
    
  rust:
    name: Rust Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-make
          components: clippy
      - name: Run linter
        run: cargo make lint
    
  docker:
    name: Docker Lint
    runs-on: ubuntu-latest
    container: pipelinecomponents/hadolint:0.27.2
    steps:
      - uses: actions/checkout@v5

      - name: Run hadolint
        run: hadolint Dockerfile
