name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  frontend:
    name: Frontend Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm run lint
    
  typescript:
    name: Typescript Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npx tsc --noEmit

  rust-clippy:
    name: Rust Clippy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  rust-toml:
    name: TOML Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-make
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend
      - name: Check TOML formatting
        run: cargo install taplo-cli --locked && taplo fmt --check Cargo.toml ../Makefile.toml
    
  docker:
    name: Docker Lint
    runs-on: ubuntu-latest
    container: pipelinecomponents/hadolint:0.27.2
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Run hadolint
        run: hadolint Dockerfile
